[package]
name = "memsed-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
description = "Linux process and memory primitives for MemSed"

[features]
default = ["webui"]
none = []
webui = ["dep:webui-rs"]

[dependencies]
#webui-rs = { git = "https://github.com/webui-dev/rust-webui", branch = "main", optional = true }
rayon = "1.11"
webui-rs = { git = "https://github.com/pscherz/pure-rust-webui", branch = "rust-rewrite", optional = true }

[[bin]]
name = "memsed-webui"
required-features = ["webui"]
